### ISSUE TITLE
SW not serving precached files

### ISSUE THREAD

**Issue by kaitsh** [sveltejs/sapper#1210] opened 2020-05-18 12:08 UTC
**Describe the bug**
The serviceworker does not serve cached files because of a missing "/" in the filenames of the `cached`-variable

**Logs**
![image](https://user-images.githubusercontent.com/8351869/82210825-c5af0f00-98dd-11ea-9a4c-c370fbfb15b4.png)

**To Reproduce**
Run `npx degit "sveltejs/sapper-template#rollup" my-app` and set a breakpoint in the serviceworker.

**Expected behavior**
The serviceworker should find the cached files and return them.

**Information about your Sapper Installation:**
- Your browser and the version: Chromium Version 81.0.4044.138 (Developer Build) (64-bit)

- Your operating system: Voidlinux Kernel 5.4.40_1

- Sapper version 0.27.13

- Svelte version 3.22.3

- Whether your application uses Webpack or Rollup: Happens with both templates.

**Severity**
annoying

**Workaround**
My current workaround is to prepend a "/" for the filenames in the `cached` variable:
```javascript
// `shell` is an array of all the files generated by the bundler,
// `files` is an array of everything in the `static` directory
const to_cache = shell.concat(files);
//const cached = new Set(to_cache);
const cached = new Set(to_cache.map(filename => `/${filename}`));
```

**Comment by antony** [comment] 2020-05-21 07:25
I was able to reproduce this using the steps above, thanks!

**Comment by antony** [comment] 2020-05-21 08:19
Right, so it looks like we can do one of two things here:

* in Sapper, prefix cached files with a slash
* In the service-worker, we can remove the slash when we look up the cache key.

As to which is the right approach, I don't know. Anybody know more about service-workers than me?

**Comment by kaitsh** [comment] 2020-05-21 20:09
I would suggest to do the first approach because this is done during compile time.

**Comment by benmccann** [comment] 2020-05-27 02:40
I don't know much about service workers, but I think that either way is fine as long as we're consistent.

**With slash**

Would make it easy to just do a direct lookup on `url.pathname`
Code to modify:
https://github.com/sveltejs/sapper/blob/b80346e2a6b6a4eded87b5c4aabafd0c7d941f44/src/core/create_app.ts#L41

**Without slash**

At first I was going to suggest that it's probably better performance to omit the slash because `service-worker.js` contains a list of every static file on the site and you'd be adding an extra character for each file that would need to be transferred over the network. But actually, once gzipped I don't think there's any difference at all (except for one character in the compression dictionary). So I guess I'd lean towards adding the slash.

**Comment by benmccann** [comment] 2020-05-27 03:09
For what it's worth, Google and Mozilla both have a leading slash in their documentation: 

https://developers.google.com/web/fundamentals/primers/service-workers#install_a_service_worker
https://developer.mozilla.org/en-US/docs/Web/API/Cache/addAll

**Comment by kaitsh** [comment] 2020-05-28 00:08
Actually I don't believe there is a significant performance difference for both approaches for reasonably sized web apps.
However, we could add the slash when we load the SW (see my workaround above). Then we do not have to send the character and we still can do the direct lookup.

**Comment by benmccann** [comment] 2020-05-28 02:13
I still think it's cleaner to have the compiler do it. Then it's less code that the user has to be aware of in the service worker

**Closed** 2020-08-06 23:15 UTC
Labels: bug
