### ISSUE TITLE
Re-exporting specific route slugs

### ISSUE THREAD

**Issue by janat08** [sveltejs/sapper#997] opened 2019-11-21 11:17 UTC
**Is your feature request related to a problem? Please describe.**
I don't wish to statically regenerate route slugs that haven't changed.

**Describe the solution you'd like**
Have the ability to compare generated dates of last export and updated dates of api.

**How important is this feature to you?**
I don't know how fast the pages get generated, but it's probably a handicap that you can't regenerate the pages as soon as they're updated.

**Additional context**
https://stackoverflow.com/questions/58973638/re-exporting-specific-route-stub-statically-generate

**Comment by pngwn** [comment] 2019-11-21 11:56
Duplicate of #601.

**Closed** 2019-11-21 11:56 UTC
