### ISSUE TITLE
Use JS label syntax "$:" without "Cannot access <obj> before initialization" error

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/sapper#1176] opened 2020-05-01 09:06 UTC
I'm using this code in my Svelte app:

```svelte
<script>
  import { query } from '@urql/svelte'

  import { MY_QUERY } from 'queries'

  $: myQuery = query({
    query: MY_QUERY,
    variables: { id }
  })
</script>

{#if !$myQuery}
  Loading...
{:else}
  Oh WOW! {$myQuery.data}
{/if}
```

Trying the same code in Sapper I get this error:

`Cannot access 'myQuery' before initialization`.

If I change the below line 

- from this: `$: myQuery = query({`

- to this: `const myQuery = query({`

it works!

**Why?**

**Comment by Conduitry** [comment] 2020-05-01 09:25
Duplicate of https://github.com/sveltejs/svelte/issues/3582

**Closed by Conduitry** 2020-05-01 09:25 UTC
