### ISSUE TITLE
service worker shell array missing .css files

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/sapper#1112] opened 2020-03-08 16:29 UTC
**Describe the bug**
The default implementation of `src/service-worker.js` imports the variable `shell` which is an array of `.js` files in the `build/client` directory that should be cached. I think the `.css` files in that same directory should also be in included in the `shell` array so they are also cached.

**Logs**
Please include browser console and server logs around the time this bug occurred.

```
The FetchEvent for "https://0c31914b.ngrok.io/client/index.51f34ae6.css" resulted in a network error response: the promise was rejected.
Promise.then (async)
(anonymous) @ service-worker.js:1
service-worker.js:1 Uncaught (in promise) TypeError: Failed to fetch
client.bfd9baf0.js:1 GET https://0c31914b.ngrok.io/client/index.51f34ae6.css net::ERR_FAILED
```

**To Reproduce**

1. Enter `npx degit sveltejs/sapper-template#rollup sapper-pwa`
1. Enter `cd sapper-pwa`
1. Enter `npm install`
1. Generate a self-signed certificate with the command
`openssl req -newkey rsa:2048 -nodes -x509 -days 365 -keyout key.pem -out cert.pem`
1. Change `src/server.js` to the following so the app is served using HTTPS:
```js
const {createServer} = require('https');
const {readFileSync} = require('fs');

import sirv from 'sirv';
import polka from 'polka';
import compression from 'compression';
import * as sapper from '@sapper/server';

const {PORT, NODE_ENV} = process.env;
const dev = NODE_ENV === 'development';

const options = {
  key: readFileSync('key.pem'),
  cert: readFileSync('cert.pem')
};

const {handler} = polka().use(
  compression({threshold: 0}),
  sirv('static', {dev}),
  sapper.middleware()
);

createServer(options, handler).listen(PORT, err => {
  if (err) {
    console.error('error', err);
  } else {
    console.info('listening for HTTPS requests on', PORT);
  }
});
```
1. Enter `npm run build`.
1. Enter `npm start`.
1. Install ngrok at https://ngrok.com/ so we can hit a non-localhost URL using HTTPS.
1. Enter `ngrok http https://localhost:3000`.
1. Browse the "Forwarding" URL that begins with "https:", not the one that begins with "http:", in Chrome.
1. Open the Chrome devtools.
1. Click the "Application" tab.
1. Select "Service Workers" in the left nav.
1. Click the "Offline" checkbox to simulate being offline.
1. In the running app, click the "blog" link.
1. Note the error displayed in the devtools Console tab where it fails to retreive the `.css` file needed for this page.

**Expected behavior**
I expected the `.css` file for this page to have been cached so the page is usable when offline.

**Information about your Sapper Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10) Chrome Version 80.0.3987.132

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc) macOS 10.15.1

- Your hosting environment: (i.e. Local, GCP, AWS, Now, etc...) none

- Sapper version (Please check you can reproduce the issue with the latest release!) 0.27.10

- Svelte version (Please check you can reproduce the issue with the latest release!) 3.19.2

- If it is an exported (npm run export) or dynamic application. - dynamic

- Whether your application uses Webpack or Rollup - Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?
I'm just trying to document how Sapper supports offline operation for my book, but it seems serious for apps that want to rely on this feature.

**Comment by mvolkmann** [comment] 2020-03-12 15:50
Perhaps I'm misunderstand the goals of the caching strategy implemented by the Sapper default service worker. I original thought it was trying to cache all the pages that do not have a preload function. But now I see that only the first page gets cached when the site is visited online. After that it seems only visited pages get cached. So if you go offline without visiting every page, so pages will not be accessible. Am I understanding this correctly?

**Comment by PatrickG** [comment] 2020-03-12 16:30
> Perhaps I'm misunderstand the goals of the caching strategy implemented by the Sapper default service worker. I original thought it was trying to cache all the pages that do not have a preload function. But now I see that only the first page gets cached when the site is visited online. After that it seems only visited pages get cached. So if you go offline without visiting every page, so pages will not be accessible. Am I understanding this correctly?

That is not correct.
Currently it pre-caches all JS-chunks and static files. Everything else (the CSS-chunks) gets cached when they are requested (the first time).

**Comment by mvolkmann** [comment] 2020-03-12 17:07
What is the benefit of caching the JS chunks from code splitting if the pages that use them (and their CSS) are not cached?

**Comment by PatrickG** [comment] 2020-03-13 06:00
That, of course, seems like it's a bug.

**Comment by kaitsh** [comment] 2020-05-06 21:24
ok, is it somehow possible to remove the reference and still have a link in the commit? I need to "force push" in the future and I?d like to avoid this referencing.

**Comment by benmccann** [comment] 2020-08-28 21:54
Closing as a duplicate of https://github.com/sveltejs/sapper/issues/625

**Closed by benmccann** 2020-08-28 21:54 UTC
Labels: duplicate, service worker
