### ISSUE TITLE
`<picture>` with native lazyload is broken when ssr

### ISSUE THREAD

**Issue by ArekBartnik** [sveltejs/sapper#1435] opened 2020-08-24 16:07 UTC
When I use `<picture>` tag with multiple `<source>` elements the Sapper app fetches all images that are on the page even when the `img` tag has `loading=lazy` attribute;

I couldn't reproduce the error in REPL (https://svelte.dev/repl/826eab50248a4f25beb19d385c935157?version=3.24.1) so I think it only occurs when SSR .

I've prepared a comparison with a NextJS app.

If you go to the `Network/Img` tab you can see that there are fewer requests for images in NextJS version.

Sapper app -> https://sapper-picture.netlify.app (https://github.com/ArekBartnik/sapper-picture)
NextJS app -> https://nextjs-picture.netlify.app (https://github.com/ArekBartnik/nextjs-picture)

Curiously, using `img` tag with `loading=lazy` attribute without `picture` works perfectly fine 🤔 Compare here https://sapper-picture.netlify.app/only-img

Turning off Service Worker didn't change anything regarding the problem.

**Comment by benmccann** [comment] 2020-08-24 16:18
Thanks for providing a way to reproduce this. I doubt this is a bug in Sapper, but more likely in Svelte. I'm going to close this because I think it is a duplicate of https://github.com/sveltejs/svelte/issues/5299

**Closed by benmccann** 2020-08-24 16:18 UTC

**Comment by thgh** [comment] 2020-08-25 11:40
Based on the DOM output, it might be a different issue: (still Svelte though)

```js
		c() {
			attr(source5, "media", "(min-width: 0px)");
			attr(source5, "sizes", source5_sizes_value = "" + (/*sizes*/ ctx[0][0] + "px"));
			attr(source5, "srcset", source5_srcset_value = "" + (imageUrl(/*sizes*/ ctx[0][0]) + " " + /*sizes*/ ctx[0][0] + "w"));
			attr(img, "loading", "lazy");
			if (img.src !== (img_src_value = imageUrl(/*sizes*/ ctx[0][2]))) attr(img, "src", img_src_value);
			attr(img, "alt", /*alt*/ ctx[3]);
			attr(img, "width", /*width*/ ctx[2]);
			attr(img, "height", /*height*/ ctx[1]);
			attr(img, "class", "svelte-1pu1x20");
			set_style(div, "padding-bottom", getProportion(/*height*/ ctx[1], /*width*/ ctx[2]));
			attr(picture, "class", "svelte-1pu1x20");
		},
```

**Comment by jimmywarting** [comment] 2020-08-26 10:13
Another theory i had was in the initial hydration part. (when svelte takes over to being more dynamic)

So my theory was/is that it removes all the old images (rendered by server) one by one - effectively removing the top most image and bringing all the bottom images into the viewport and then triggering the loading before it gets removed completely. after witch svelte takes over and inserts new images.

I don't know if this is the case. I'm new to the hole svelte world. But i can't back up this idea, since i don't know how the core of all things works. 

I Tried setting breakpoints on DOM changes in devtool, but there where too many changes happening to even grasp what was happening. (Header element was tossed around - disappearing and reappear among other things - lots of thing where being removed and appended)

I don't know if it tries to reuse dom elements or if it's replace it all together. but my "assign all props at once" in sveltejs/svelte#5299 did seem to solve it for me, so my assumption is that they are reused?

a better approach would maybe be to clone of the hole DOM and make all modifications to them offscreen and then later replace all off it in one batch in the initial hydration boot up. 

> create a set of DOM elements that are not currently inserted in the DOM, make all your modifications to them and then with one operation, insert them into the DOM
[Executing multiple DOM updates with JavaScript efficiently](https://stackoverflow.com/a/37040384/1008999)

**Comment by jimmywarting** [comment] 2020-08-26 10:19
One thing i notice in @thgh DOM output was that with, height, class and style are assigned after src have been set...
I don't know if that might be a problem... but it's important that all `<img>` are not visible all at once. So it's better to assign src at the very last step.
