### ISSUE TITLE
[Need help] Sapper serve 200 ok always

### ISSUE THREAD

**Issue by xncbf** [sveltejs/sapper#1072] opened 2020-01-25 02:45 UTC
I created register page, and submit without any input. 
I got 200 ok though backend server raise 400 reseponsed
how can i get right status on my js code?

![image](https://user-images.githubusercontent.com/9462045/73115277-30bb8b00-3f67-11ea-9719-30c74f296823.png)

![image](https://user-images.githubusercontent.com/9462045/73115300-7710ea00-3f67-11ea-9d62-420361111396.png)

![image](https://user-images.githubusercontent.com/9462045/73115308-87c16000-3f67-11ea-8263-8e329886e7c0.png)

below image is api call to my backend server and responsed 400 status
![image](https://user-images.githubusercontent.com/9462045/73115347-0f0ed380-3f68-11ea-9d48-5f57a23d9048.png)

**Comment by antony** [comment] 2020-02-01 11:21
This issue is very confusing, I'm seeing three different URLs, so it's hard to say that the endpoint you claim returns 400 is actually being hit.

If you are able to reproduce this issue with a small self-contained Sapper application, then please attach or link the repro here and re-open, and we will try to help. Alternatively come and chat to us in the discord if you have the application publicly available.

For now I'm closing this issue because it feels strongly like user-error and not something we can help you with.

**Closed by antony** 2020-02-01 11:21 UTC

**Comment by xncbf** [comment] 2020-02-01 11:45
That is simple. you can reproduce on realworld sapper
https://realworld.svelte.dev/login.
Try login with wrong email or password.
you will recieve 200 ok on developer tools.

**Comment by antony** [comment] 2020-02-01 11:49
That's because the API for the realworld app returns a 200 even if there is an error.

I have an authentication API which returns 400 on bad payloads, sapper receives a 400 no problem. Same with all other error codes.

**Comment by xncbf** [comment] 2020-02-01 12:06
Can you share part of code?
