### ISSUE TITLE
_layout styles don't get applied on _error pages

### ISSUE THREAD

**Issue by IcyFoxe** [sveltejs/sapper#1480] opened 2020-09-03 07:53 UTC
After cloning and installing the Sapper Rollup template, _layout styles don't get applied on _error pages, resulting in broken appearance. This however is not a problem in the Webpack template.

Any clue what could be the issue and how to fix it?

**Comment by rodoch** [comment] 2020-09-03 12:48
I believe this is a duplicate of  #1472 and a fix has been merged to master with #1474.

**Comment by Jayphen** [comment] 2020-09-04 15:09
This should be fixed in the recent 0.28.4 release.

**Comment by IcyFoxe** [comment] 2020-09-04 15:12
I just updated and everything looks good! Awesome!

**Closed** 2020-09-04 15:20 UTC
