### ISSUE TITLE
Sirv required also if using static-serve

### ISSUE THREAD

**Issue by webfrank** [sveltejs/sapper#1323] opened 2020-07-16 15:57 UTC
**Describe the bug**
I switched from sirv to staic-serve but in server.js there is a static require('sirv')

**Logs**
internal/modules/cjs/loader.js:589
    throw err;
    ^

Error: Cannot find module 'sirv'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:587:15)
    at Function.Module._load (internal/modules/cjs/loader.js:513:25)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/francesco/html/booqr/__sapper__/dev/server/server.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
> Server crashed

generated server.js:

'use strict';
  
function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }

require('sirv');
var serveStatic = _interopDefault(require('serve-static'));
var polka = _interopDefault(require('polka'));
var compression = _interopDefault(require('compression'));

**To Reproduce**
exchange sirv with static-serve and try to compile

**Expected behavior**
I should be able to exchange the middleware

**Information about your Sapper Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)

- Your hosting environment: (i.e. Local, GCP, AWS, Now, etc...)

- Sapper version (Please check you can reproduce the issue with the latest release!)

- Svelte version (Please check you can reproduce the issue with the latest release!)

- If it is an exported (npm run export) or dynamic application.

- Whether your application uses Webpack or Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by benmccann** [comment] 2020-07-22 23:05
`__sapper__/build/server/server.js` is just generated from the code you have in your `src/server.js`, so if you're seeing `sirv` in there you need to update `src/server.js` and rebuild

**Comment by webfrank** [comment] 2020-07-23 07:12
Hi, I doubled checked serve.js and there is no reference to sirv. I had to completely delete __sapper__ forlder and let recreate to get rid of sirv.

**Comment by benmccann** [comment] 2020-07-23 12:48
Ok. Not sure why it wasn't picking up your change, but I can't reproduce the issue and it sounds like it's solved for you. Do you want to close this issue?

**Closed** 2020-07-24 19:49 UTC
