### ISSUE TITLE
Optimize prefetch algorithm

### ISSUE THREAD

**Issue by vladejs** [sveltejs/sapper#140] opened 2018-02-26 02:52 UTC
I noticed that everytime I hover over a prefetch link, it makes an http request to the server.
Is there any way it make the call once and cache the result?

**Comment by Rich-Harris** [comment] 2018-02-28 00:55
Technically no, because state might have changed between the first hover and the second, so to guarantee correctness it's necessary to make a new request each time.

The idea is that you'd use a service worker to cache responses on the client side if they're not going to change, though obviously it's not ideal for all cases. Perhaps there's some configuration we could add somewhere.

**Comment by vladejs** [comment] 2018-03-01 02:23
Thanks for the response @Rich-Harris , will leave it open for now if you don't mind

**Comment by Rich-Harris** [comment] 2018-03-18 12:53
Been experimenting with a more conservative approach to prefetching that I now plan to implement: https://svelte.technology/repl?version=1.57.4&gist=1391a7280e16070d76efb0485c643689

Instead of prefetching links on hover, it tracks mouse movements. When the mouse *stops* moving, we do an `elementsFromPoint` check to see if any `<a>` elements are under the mouse; if so, prefetching happens. (May have to use an alternative technique for Safari though, it doesn't look like it supports `elementsFromPoint`. Gah.)

A 20ms timeout to determine whether the mouse has stopped moving appears to be enough to avoid false positives. In my tests, this completely avoids accidental prefetches caused by the mouse 'brushing' over links.

Touch behaviour would stay the same — prefetching happens on `touchstart`.

**Comment by Rich-Harris** [comment] 2018-03-18 13:07
Version that works in Safari: https://svelte.technology/repl?version=1.57.4&gist=fbb15a059ac44bbf67452be746185853. This is probably a more logical approach.

**Comment by vladejs** [comment] 2018-03-20 16:30
Why not just collect all a-prefetch links and trigger them after page is ready?
The rel=prefetch attr is intentionally put by the developer anyways.

**Comment by Rich-Harris** [comment] 2018-03-20 17:19
It's a bad fit for content sites, like https://hn.svelte.technology/ — realistically, you're only going to click one or two links, so fetching all that data is wasteful and could even slow things down. There's a `prefetch` function that you can use for programmatic control if you want to do that:

```html
<script>
  import { prefetch } from 'sapper/runtime.js';

  export default {
    oncreate() {
      const links = document.querySelectorAll('a[rel="prefetch"]');
      [...links].forEach(a => {
        prefetch(a.href);
      });
    }
  };
</script>
```

**Comment by vladejs** [comment] 2018-03-22 16:46
Yes, you are right. But I mean to do that only for internal pages, for
example, header links.

Links that has href to external sources should maintain the hover behaviour

**Comment by Rich-Harris** [comment] 2018-09-02 22:49
Will close this as I don't anticipate making further changes to how prefetching works — AFAIK it isn't possible to prefetch external links, so the existing tools will have to suffice.

**Closed by Rich-Harris** 2018-09-02 22:49 UTC
