### ISSUE TITLE
this.fetch should { credentials: "include" } per default, if it's an internal resource.

### ISSUE THREAD

**Issue by MatthiasGrandl** [sveltejs/sapper#1026] opened 2019-12-12 10:37 UTC
On SSR the preload always threw an error and it took me quite a while to figure out, that it's because my credentials didn't get send for the auth middleware. I really think this should be the default for `this.fetch` on internal routes. Opinions?

**Comment by benmccann** [comment] 2020-05-28 02:46
Agree. It is the default on the browser. It's a bug that the server doesn't match the browser. There's a pending PR for it: https://github.com/sveltejs/sapper/pull/882

**Comment by Conduitry** [comment] 2020-06-01 16:12
Duplicate of #881, which has been fixed on master by #882.

**Closed by Conduitry** 2020-06-01 16:12 UTC
Labels: enhancement
