### ISSUE TITLE
HTML output is incorrect using sapper export

### ISSUE THREAD

**Issue by vndre** [sveltejs/sapper#1455] opened 2020-08-29 15:31 UTC
**Describe the bug**
the _index.html_ created using `sapper export` is missing </ body> and </ html> closing tags

*Sapper v0.28.2*

Here is an extract of my generated html file:

```
<body>
  <div id=sapper>
    <main class=svelte-18unutu>
    </main>
    <footer class=svelte-186b8as>
    </footer> 
  </div>
                        <script>__SAPPER__={baseUrl:"",preloaded:[void...
                        </script> <noscript> <img
                          src="https://www.facebook.com/tr?id=&ev=PageView&noscript=1" height=1
                          style=display:none width=1> </noscript>

--- END OF FILE
```

template.html:

```
<body>
	<!-- The application will be rendered inside this element,
	     because `src/client.js` references it -->
	<div id='sapper'>%sapper.html%</div>

	<!-- Sapper creates a <script> tag containing `src/client.js`
	     and anything else it needs to hydrate the app and
	     initialise the router -->
	%sapper.scripts%
	<noscript>
		<img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=&ev=PageView&noscript=1" />
	</noscript>
</body>
</html>

```

**To Reproduce**
npx degit "sveltejs/sapper-template#rollup" my-app
cd my-app
npm i
npm run export

**Expected behavior**
file should end with expected closing tags

**Comment by Conduitry** [comment] 2020-08-29 18:10
Duplicate of #1061, #1161, and maybe others. Exported sites have their HTML minified, and this is by design.

**Closed by Conduitry** 2020-08-29 18:10 UTC
Labels: export

**Comment by vndre** [comment] 2020-08-29 18:20
I don't think you should leave any tag open, they weren't made so "by design". Although the hmlt specs says it is valid syntax it also informs about possible bugs because unclosed tags.

From the specs:
"A body element's end tag may be omitted if the body element is not immediately followed by a comment."

I can't add comments to the end of the file because it will turn to invalid syntax.

**Comment by GitGangGuy** [comment] 2020-09-02 23:01
@vndre If the html spec says it is valid, then it is valid. The whole point of minification is to reduce the file size to the bare minimum without breaking anything (i.e. staying spec-compliant).
