### ISSUE TITLE
redaction of link tags in document head

### ISSUE THREAD

**Issue by tidiview** [sveltejs/sapper#1272] opened 2020-06-15 08:06 UTC
a little change in `template.html` from:

`<link rel='stylesheet' href='global.css'>`
to
`<link rel='preload' as='stylesheet' href='global.css'>`

has been not less than **minus 0.3 s** on PageSpeed Insight ♫
(from 1.4 s before interactivity to 1.1 s).

Therefore, would not it be a good thing to change the redaction of those link tags accordingly, not only in `template.html` but also in the generated tags like this one:

![image](https://user-images.githubusercontent.com/14911996/84632320-0014c780-aeef-11ea-8908-3af655bebcc7.png)

Hope this could make sapper even better ☆

**Comment by tidiview** [comment] 2020-06-15 13:28
There have been some exchanges on Discord around this.
It is related to this part of `code`.
`sapper/runtime/src/server/middleware/get_page_handler.ts`
`line 315`
Thanks goes to @Rainlife there.
https://github.com/sveltejs/sapper/blob/857a3e786ef3bab13445c1cae685c7493d3b7062/runtime/src/server/middleware/get_page_handler.ts#L315

**Comment by tidiview** [comment] 2020-06-15 13:38
This recommandation was made from very basics indications given by [PageSpeedInsights](https://developers.google.com/speed/pagespeed/insights/).
Probably this is related to the way of handling the asset towards the main document thread.

**Comment by benmccann** [comment] 2020-06-15 13:42
This is a duplicate of https://github.com/sveltejs/sapper/issues/408

**Closed** 2020-06-15 18:19 UTC
