### ISSUE TITLE
Load translations both on SSR and browser rendering

### ISSUE THREAD

**Issue by hydroper** [sveltejs/sapper#1433] opened 2020-08-23 21:36 UTC
**Is your feature request related to a problem? Please describe.**
There's no way to detect locale as I browsed on the docs.

**Describe the solution you'd like**
A way to access the locale or Request from the server router (so I can derive the Accept-Language HTTP header).

**Describe alternatives you've considered**
Rendering only one language for the search engines.

**How important is this feature to you?**
It's easy to integrate it in my codebase.

**Additional context**

**Comment by benmccann** [comment] 2020-08-23 21:40
This sounds like a duplicate of https://github.com/sveltejs/sapper/issues/576

**Closed by benmccann** 2020-08-23 21:40 UTC
