### ISSUE TITLE
Maybe remove "military grade" from the tag line? 

### ISSUE THREAD

**Issue by damassi** [sveltejs/sapper#506] opened 2018-10-30 21:41 UTC
Feels a bit violent... Maybe something else could communicate the sturdiness of this lib?

**Comment by Rich-Harris** [comment] 2018-10-30 21:45
We probably are going to change this, yes — there's a redesign pending which this was kind of waiting for. In any case I'll close this issue as it's a dupe of https://github.com/sveltejs/sapper/issues/263 — thanks

**Closed by Rich-Harris** 2018-10-30 21:45 UTC
