### ISSUE TITLE
"Cannot read property 'split' of null" issue with svelte-preprocess and scss

### ISSUE THREAD

**Issue by riccardolardi** [sveltejs/sapper#1496] opened 2020-09-08 16:18 UTC
The same works in pure Svelte but does throw an error in Sapper:

An imported scss file in _layout.svelte:

```
<style type="text/scss">
  @import "../style/style.scss";
</style>
```

```
.my-div {
  &.my-class {
    color: blue; // this throws error
    another-div {
      color: blue; // this doesn't
    }
  }
}
```

It seems that when using the scss ampersand, directly setting css throws this error `Cannot read property 'split' of null`. The same works fine in pure Svelte. Rollup is configured like in https://github.com/pngwn/sapper-scss/blob/master/rollup.config.js

Any hint on this?

**Comment by Conduitry** [comment] 2020-09-08 16:22
Do you have a repo that can be cloned to reproduce this?

**Comment by riccardolardi** [comment] 2020-09-08 16:26
@Conduitry here you go https://github.com/riccardolardi/sapper-scss

**Comment by benmccann** [comment] 2020-09-08 16:30
You need to setup `sveltePreprocess` to handle `scss`

**Comment by riccardolardi** [comment] 2020-09-08 16:32
@benmccann can you elaborate? Scss compiling works fine, mentioned problem aside...

**Comment by benmccann** [comment] 2020-09-08 16:45
Ah, nevermind. I thought you would have to enable sass with some setting, but it doesn't look like that's necessary from the docs. Can you share more of the error you're getting such as the stack trace? This seems unlikely to be an issue in Sapper even if it doesn't occur on your vanilla svelte project. Perhaps the folks over at https://github.com/sveltejs/svelte-preprocess would know more

**Comment by riccardolardi** [comment] 2020-09-08 16:47
@benmccann full error stack trace:

```
➜ npm run dev

> TODO@0.0.1 dev /Users/riccardolardi/Code/sapper-scss
> sapper dev

✗ server
Cannot read property 'split' of null
✗ client
Cannot read property 'split' of null
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/Users/riccardolardi/Code/sapper-scss/__sapper__/dev/server/server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
> Server crashed
```

**Comment by benmccann** [comment] 2020-09-08 16:51
Do you get any more details if you run `npm run build`?

**Comment by riccardolardi** [comment] 2020-09-08 16:52
@benmccann 

```
➜ npm run build

> TODO@0.0.1 build /Users/riccardolardi/Code/sapper-scss
> sapper build --legacy

> Building...

[!] (plugin svelte) TypeError: Cannot read property 'split' of null
/Users/riccardolardi/Code/sapper-scss/src/components/Nav.svelte
TypeError: Cannot read property 'split' of null
    at test_attribute (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23486:34)
    at attribute_matches (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23584:14)
    at block_might_apply_to_node (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23458:19)
    at apply_selector (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23400:14)
    at Selector$1.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23297:10)
    at /Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23668:54
    at Array.forEach (<anonymous>)
    at Rule$1.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23668:25)
    at Stylesheet.apply (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:23939:20)
    at new Element$1 (/Users/riccardolardi/Code/sapper-scss/node_modules/svelte/compiler.js:24709:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TODO@0.0.1 build: `sapper build --legacy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TODO@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/riccardolardi/.npm/_logs/2020-09-08T16_51_41_784Z-debug.log
```

**Comment by riccardolardi** [comment] 2020-09-08 16:53
npm debug log:

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/riccardolardi/.nvm/versions/node/v12.18.3/bin/node',
1 verbose cli   '/Users/riccardolardi/.nvm/versions/node/v12.18.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle TODO@0.0.1~prebuild: TODO@0.0.1
6 info lifecycle TODO@0.0.1~build: TODO@0.0.1
7 verbose lifecycle TODO@0.0.1~build: unsafe-perm in lifecycle true
8 verbose lifecycle TODO@0.0.1~build: PATH: /Users/riccardolardi/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/riccardolardi/Code/sapper-scss/node_modules/.bin:/usr/local/mysql/bin:/Users/riccardolardi/.nvm/versions/node/v12.18.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
9 verbose lifecycle TODO@0.0.1~build: CWD: /Users/riccardolardi/Code/sapper-scss
10 silly lifecycle TODO@0.0.1~build: Args: [ '-c', 'sapper build --legacy' ]
11 silly lifecycle TODO@0.0.1~build: Returned: code: 1  signal: null
12 info lifecycle TODO@0.0.1~build: Failed to exec build script
13 verbose stack Error: TODO@0.0.1 build: `sapper build --legacy`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/riccardolardi/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/Users/riccardolardi/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid TODO@0.0.1
15 verbose cwd /Users/riccardolardi/Code/sapper-scss
16 verbose Darwin 19.6.0
17 verbose argv "/Users/riccardolardi/.nvm/versions/node/v12.18.3/bin/node" "/Users/riccardolardi/.nvm/versions/node/v12.18.3/bin/npm" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error TODO@0.0.1 build: `sapper build --legacy`
22 error Exit status 1
23 error Failed at the TODO@0.0.1 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by benmccann** [comment] 2020-09-08 16:58
I'm going to close this in favor of https://github.com/sveltejs/svelte-preprocess/issues/241. The only thing Sapper does with CSS is split it up into different files, but it wouldn't insert or remove special characters like `&`

**Closed by benmccann** 2020-09-08 16:58 UTC

**Comment by kaisermann** [comment] 2020-09-08 17:17
This seems to be happening because some elements have their classes possibly defined as `null` (ex: `class={!segment ? 'is-intro' : null}`), which is triggering the `split' of null` message. Should the compiler allow a `null` class value? Or maybe normalize falsy values to an empty string?

**Comment by riccardolardi** [comment] 2020-09-08 17:20
I see! Thanks @kaisermann 

Since I'm new to Sapper/Svelte I'm not sure if that's the best practice way to define conditional classes. Is there another way which doesn't let the class be null?

**Comment by benmccann** [comment] 2020-09-08 17:22
I haven't worked on the compiler at all, so I don't really have any input or insight there since it's not really a Sapper issue
