### ISSUE TITLE
Images are requested twice and not cached

### ISSUE THREAD

**Issue by mhatvan** [sveltejs/sapper#1310] opened 2020-07-09 12:49 UTC
**Describe the bug**
Not sure if it is a bug, not implemented yet or intended behaviour due to SSR, but here we go:

Images are requested twice, as can be seen in the screenshot below. 
Once by the server and once when the client takes over, I assume?

Can this be avoided somehow? It leads to a lot of unnecessary download overhead for the user.

What I am currently using is `await import` the component and therefore skip SSR, but then there is a moment of blank page, before the content is there.

Additionally, on consecutive navigating to the page, the images get loaded again, this time once only, but the request is unnecessary since the content is static.

**Expected behavior**
Images load once and get cached to avoid future requests.

**Information about your Sapper Installation:**
- Your browser and the version: Chrome 83.0.4103.116

- Your operating system: Ubuntu Linux 20.04

- Sapper version: 0.27.16

- Svelte version: 3.24.0

- while running `yarn dev`

- Rollup

**Severity**
Annoying and bad UX, since user sees content rendering after short blank page.

**Additional context**

![2020-07-09_14-39](https://user-images.githubusercontent.com/16797721/87041658-db142b80-c1f2-11ea-98e3-61d18a4fe510.png)

**Comment by benmccann** [comment] 2020-07-09 15:19
This sounds like a duplicate of https://github.com/sveltejs/sapper/issues/1210

**Comment by ajbouh** [comment] 2020-07-10 16:52
Is it still a duplicate of #1210 if it happens even when the service worker is disabled?

**Comment by benmccann** [comment] 2020-07-10 16:57
No. But also make sure you "unregister" the service worker. If you ever had the service worker enabled then it will stick around permanently until you do so

**Comment by ajbouh** [comment] 2020-07-10 22:21
In the absence of a service worker, what's the recommended solution / workaround to this SSR/client-side re-rendering?

Seems like this might force us to revisit the current simplistic approach to hydration in the near term. Thoughts?

**Comment by benmccann** [comment] 2020-07-10 22:32
Ah, if you're talking about hydration, this isn't really an issue in Sapper, so we can close this issue. There are some issues over in the Svelte repo to track this: https://github.com/sveltejs/svelte/issues/4975

Personally I just turn off SSR and do only CSR. Though my PR for that hasn't been merged yet, so it's not quite an out-of-the-box solution yet

**Closed** 2020-07-11 16:16 UTC
