### ISSUE TITLE
Decrease the delay between the page switch and page title update

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/sapper#1181] opened 2020-05-04 12:56 UTC
**Is your feature request related to a problem? Please describe.**
While working on my first Sapper project I noticed that there is a pretty big delay when switching routes between the actual page getting drawn on screen and the tab <title> visually changing.

This also happens on the official website when switching between the Docs page and landing page.
https://sapper.svelte.dev/

In my app when running in dev mode the delay is almost about 800ms.
When looking at the sapper website it is about 400ms to 700ms.

_I'm eyeballing these numbers. Take them with a grain of salt. The delay is very noticeable tho._

**Describe the solution you'd like**
A optimization to decrease this delay so the website feels more responsive.

**Describe alternatives you've considered**
Maybe force it through some life-cycle hook? Haven't tested this yet.

**How important is this feature to you?**
Kinda important in the context of perceived performance/quality but not a project-breaking problem or anything.

**Additional context**
Browser: Latest version of Edge (chromium)
No Extensions installed and running the latest version of sapper and all its dependencies (npm update)

I also tried to see if it may be resolved when using the raw export instead of a node server and that doesn't seem to make any difference. Also loading the website from local or a remote server doesn't change the delay at all.

**Comment by fhucho** [comment] 2020-05-10 12:20
I would like this fixed as well. In Safari the title switch is immediate.

**Comment by benmccann** [comment] 2020-08-28 20:49
I don't see this when clicking between https://sapper.svelte.dev/ and https://sapper.svelte.dev/docs. Is this still happening?

I wonder if it's fetching the data first and waiting for the data to be returned? You could try setting sleep statements in your server routes to confirm if that's what's causing this. It'd help to know the cause

**Comment by UltraCakeBakery** [comment] 2020-08-29 12:06
![gP5fIM1NR6](https://user-images.githubusercontent.com/12383587/91636417-9a6dad00-ea00-11ea-9a67-1457711c78b7.gif)
Here is a gif of what i see. I switch between FAQ / Docs. In my own applications I experienced the same.

**Comment by benmccann** [comment] 2020-08-31 02:53
I'm still having a little bit of a hard time understanding what is happening vs what you want to have happen (especially since I can't see the link being clicked in the gif). Is the issue that the title switches and then the page contents doesn't switch until later? Or is the issue that you click a link and then it takes awhile before the title switches?

**Comment by UltraCakeBakery** [comment] 2020-08-31 06:51
When you click a link, there is a delay between the content on the page appearing / being rendered and the title of the page updating.

Here is a screen recording of the sapper website on my work computer. The delay here is less noticeable. 
In my experience it can take up to 3 whole seconds for the page to update. In this gif it is more like 300ms / 400ms.

![PWPYu2b0aP](https://user-images.githubusercontent.com/12383587/91690686-affce700-eb66-11ea-9dd5-8da4b964dd1c.gif)

**Comment by UltraCakeBakery** [comment] 2020-08-31 06:55
When you click a link, there is a delay between the content on the page appearing / being rendered and the title of the page updating.

Here is a screen recording of the svelte/sapper website on my work computer. The delay here is less noticeable.
In my experience it can take up to 3 whole seconds for the page to update. In this gif it is more like 300ms / 400ms. Content on the page updates instantly when clicking.

![21eG2MakCG](https://user-images.githubusercontent.com/12383587/91691229-94461080-eb67-11ea-86a3-dbe9d77bcd97.gif)

**Comment by benmccann** [comment] 2020-08-31 15:35
Here's where the title is defined:
https://github.com/sveltejs/sapper/blob/bd0ce5a489cc1b386d4c86fc9fb8f67af88ca489/site/src/routes/faq/index.svelte#L15

I don't really see anything in Sapper that would cause it to load after everything else. I wonder if this is an issue in Svelte where that is loaded last for some reason. It'd be interesting to experiment on some non-Sapper sites and see if you see the same behavior. E.g. do you also see it on https://routify.dev/?

**Comment by websocket98765** [comment] 2020-08-31 17:19
Since client-side routing is used, page title must be updated via JavaScript. Maybe this issue is actually in Svelte?

- <https://github.com/sveltejs/svelte/search?q=%22document.title%22>
- <https://github.com/sveltejs/svelte/blob/cd21acfb3cae574b81f2f417331993374222a9de/src/compiler/compile/render_dom/wrappers/Title.ts>

**Comment by UltraCakeBakery** [comment] 2020-08-31 19:18
> Here's where the title is defined:
> https://github.com/sveltejs/sapper/blob/bd0ce5a489cc1b386d4c86fc9fb8f67af88ca489/site/src/routes/faq/index.svelte#L15
> 
> I don't really see anything in Sapper that would cause it to load after everything else. I wonder if this is an issue in Svelte where that is loaded last for some reason. It'd be interesting to experiment on some non-Sapper sites and see if you see the same behavior. E.g. do you also see it on https://routify.dev/?

I experience the exact same behavior on Routify. However, I just tried out Firefox and Internet Explorer 11. There is no issue there. So maybe it is a webkit based browser problem?..

Sadly I do not have chrome installed. I normally, and in both gifs, use the latest version of the new microsoft edge browser.
Does anyone on Chrome experience the same thing?

**Comment by benmccann** [comment] 2020-08-31 19:21
I don't see much lag in Chrome. I don't have Windows or Edge to be able to test there

Anyway, if this is happening in Routify too then it's not an issue in Sapper, so I'm going to go ahead and close this

**Closed by benmccann** 2020-08-31 19:21 UTC
Labels: invalid

**Comment by websocket98765** [comment] 2020-08-31 20:58
Maybe the issue could be transferred to Svelte, instead of closed? Given it seems to be an issue with Svelte since it was confirmed in Routify too.

**Comment by benmccann** [comment] 2020-08-31 22:05
It's not clear to me if it's an issue in Svelte or in Edge. I think a bit more investigation might help.

It's probably cleaner to file a new issue that highlights just the important details from this thread

**Comment by Wolfr** [comment] 2020-09-02 21:25
I don't see the delay that you are talking about.
