### ISSUE TITLE
SPA mode

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sapper#383] opened 2018-08-28 11:25 UTC
A few people have asked if Sapper has a mode where it *doesn't* server-render components, but instead just handles the routing and serves a blank page for the client-side app to fill in.

I don't think it makes sense in many situations, but it could make sense in some. We could have something like this:

```js
.use(sapper({
  manifest,
  ssr: false
}))
```

It would also be useful perhaps to have a hybrid mode that SSRs as much as it can but also creates a blank 200.html page (or whatever) to cover pages that can't be rendered ahead of time (some services like Surge allow you to use 200.html to mean 'any route that doesn't have its own page already).

**Comment by kylecordes** [comment] 2018-08-28 13:33
Most ideally Sapper build output would include two different "versions" of the server:

* The fully SSR server as exists now
* a simplified server that only includes the non-SSR-render endpoints, in conjunction with a set of statically rendered files which can be served via CDN or any other non-Node, non-SSR  web server machinery.

Obviously the essence are is optimal for minimizing client-side wintertime and many other things. But there are plenty of use cases where the SSR matters little, and the convenience of static serving matters a lot. Producing both kinds of output (especially for a test suite with a nontrivial app) would also guide Sapper development down a path of useful rigor, I think.

**Comment by Rich-Harris** [comment] 2018-08-28 15:38
@akaufmann I definitely have some sympathy for that view. The counter-argument is that creating such an alternative would be a *lot* of work, especially if it were to have feature parity with Sapper, whereas adding this feature to Sapper would require almost none — it essentially consists of changing [this line](https://github.com/sveltejs/sapper/blob/3d39836cfb9f7cfb29f262d8985e9bc518669d50/src/middleware.ts#L505):

```diff
-.replace('%sapper.html%', () => html)
+.replace('%sapper.html%', () => ssr ? html : '')
```

(You'd also want to avoid running the `preload` functions, and apps would want to set `hydrate: false` in the client webpack config as a small optimisation, but that's basically it.)

**Comment by antonheryanto** [comment] 2018-08-28 15:55
other scenario is that we are not running node as backend and just require spa mode (simple apps) but still develop using sapper, but the export result (which is not static but load backend data) are only rendered index.html and client js

**Comment by akaufmann** [comment] 2018-08-28 15:57
@Rich-Harris That's really not much to adjust 😃 I already thought that this feature is at the expense of users who use Sapper as an SSR framework.

**Comment by kylecordes** [comment] 2018-08-28 16:51
Here is the use case I was thinking of:

* Begin development with Sapper, such that the build output is just static files to be deployed - to a company's existing serving infrastructure. (XHRing to an existing API backend.)
* Project grows and become successful... in an environment where it might not have gotten off the ground, if the very first deployment required deploying a Node server.
* The need for SSR rises.
* The entrenched application is now important enough to warrant server-code deployment.
* ... and Sapper built output already supports this with no code change.

**Comment by timhall** [comment] 2018-09-01 13:58
Just for reference, I was able to get this to work on one of my projects with: https://github.com/timhall/sapper-spa

It basically returns an empty html for components/routes and clears out preloaded data so that the preload function runs client-side. It’s working great for building an Electron app (I attempted to run the sapper dev server from the context of Electron, but there were a few too many issues).

I like the `ssr: false` option, it matches well with svelte’s option and thanks for the note on `hydrate`, I need to make sure to turn that off.

**Comment by lillem4n** [comment] 2019-08-16 14:03
When adding this, I'd love a hydrate-option then as well. Especially when developing the 500-errors on server-side just swishes by sometimes and the client hydration cleans it up. Now it's easier to disable javascript in the browser and work from there, but I like options. :)

**Comment by hepiBatman** [comment] 2019-08-16 21:28
Wasm Emscripten does not work for SSR. As web-assembly use is more prominent, support for non-SSR will be more in demand.

**Comment by tomByrer** [comment] 2019-08-17 16:01
> Wasm Emscripten does not work for SSR.

WASM sure can work in SSR:
[Cloudflare Workers](https://github.com/tomByrer/awesome-cloudflare-workers)
[Rust's Percy](https://github.com/chinedufn/percy)
& I think there is some GoLang WASM stuff that can SSR.

Irregardless, 'hybrid SSR-SPA mode' would be very useful.  Since Sappier lacks this mode, it makes Gatsby look more attractive for some projects to me.

**Comment by hepiBatman** [comment] 2019-08-20 07:29
WASM probably can but not with Emscripten. I can only get it working with sapper by running it on client as Worker.

https://github.com/sveltejs/sapper/issues/849

**Comment by jakobrosenberg** [comment] 2019-09-21 11:43
SSR is about SEO and user experience. But what about developer experience? That may be why most of us are here. I assume.

Forcing SSR (in some cases)
1. increases build-time
2. adds more moving parts
3. obfuscates debugging and troubleshooting
4. complicates authentication
5. complicates offline-first apps
6. complicates security (with  SPA only endpoints have to be secure)
7. delays page load according to the slowest endpoint response

While odds are that I'm wrong about some of the claims, there are a lot of reasons to not force SSR. Especially in developer mode.

When I run ``npm run build`` I build a bundle that's optimized for the end user. When I run ``npm run dev`` I run a process that's optimized for development. Forcing SSR is like forcing minifiers, obfuscators and other build tools. Sure, I can check that they work every time I save a file, but do I want to? That's not how testing is done anyway.

Currently my server build-times increase gradually to 10+ seconds until I restart Sapper with ``npm run dev``. Without forced SSR (at least in dev mode) the issue would be easier for me to debug. Hell, the issue probably wouldn't even be there to begin with.

**Comment by sw-yx** [comment] 2019-10-07 13:52
i'm on the side of this being out of scope for sapper. there are [templates](https://github.com/ryanatkn/awesome-svelte-resources#templates) and [cli tools](https://github.com/ryanatkn/awesome-svelte-resources#cli-tools) that do the SPA thing and only the SPA thing. 

also using sapper idiomatically means colocating data fetch routes, which isn't usable anymore in SPA mode. so you start having to write apps differently under SPA mode, instead of being just a CLI flag.

**Comment by khrome83** [comment] 2019-10-10 11:24
I gotta be honest, why?

Why would you not just export the site if your going to the trouble to build it? What is the limitation that you need a SPA only mode?

This seems a better use case for Svelte/Svelte-router than Svelte/Sapper to be honest...

The point of Sapper is file system routing. That means having files for a server to process, or export by crawling the app running on a temporary server and writing the responses to disk.

---
Zane Milakovic

**Comment by jakobrosenberg** [comment] 2019-10-10 15:30
> The point of Sapper is file system routing

You don't need SSR for file system routing. In fact, this was my initial concern - that you have to buy into all the issues that come with SSR just to use a file system router.

I since wrote [svelte-filerouter](https://github.com/jakobrosenberg/svelte-filerouter) and ported my projects to Svelte.

For me it makes no difference now whether Sapper adopts SPA feature, but for anyone wanting an official, maintained library, I can see why this is a concern.

**Comment by nitro52** [comment] 2019-11-14 09:31
I'd be interested in just the client side routing as our backend is .net at the moment. Adding a node backend would be overkill. Perhaps if you could do the SSR at built time?

**Comment by nitroboy720** [comment] 2019-12-05 23:09
+1 Would greatly appreciate if there was a SPA mode!

**Comment by akauppi** [comment] 2019-12-11 22:16
I came to Sapper in order to make an SPA - gosh, even the name SAPper is so close come to think of it. Happy I found this discussion. Not sure any more, whether I'm using the right tool but at least I know about the concerns and the haziness.

Won't toss my opinion here, since I'm too newbie for Sapper to understand the depth of the design decisions, and focus of the project. I came for the file system routing, and would likely have implemented the SPA using Sapper. Now, I'll check the mentioned `svelte-router` and `svelte-filerouter` instead.

ps. Once the focus is clear, please check that the Sapper web site remains in sync with it.

**Comment by sido420** [comment] 2020-01-13 06:14
Whats the ETA on this? 

Trying to use the same sapper code base for both web app and Cordova app. Is this something already supported? Are there any techniques that I can use to make it work? Is SPA the solution for my use case? My app is dynamic and requires authnetication and user login etc so exporting the app is not going to work.

**Comment by rustybuddha** [comment] 2020-01-13 14:10
Atleast give option to disable SSR for a specific route which can't be rendered ahead of time. I can't have my entire website ditch SSR, just for the one route which can't be SSR (throwing many errors on server-side which otherwise works on client-side)

Solving this problem at route level should be easier, instead of, at component level. (I don't know enough to stand by this, just a speculative opinion)

**Comment by evdama** [comment] 2020-01-18 14:47
I really enjoy using Svelte as well as Sapper, but integrating Sapper with Firebase is currently a real headache because of SSR which I think is great but also has its issues with e.g. libs such as Firebase https://github.com/codediodeio/sveltefire/issues/4

So maybe really having the option to disable SSR for particular routes could ease a lot of pain and simplify the developement experience for may developers.

Long term, maybe since I'm also running my Sapper SSR function inside a firebase cloud function which in turn runs on node 10 atm, the upgrade to node 13 with esm support will improve things a lot...

**Comment by markus** [comment] 2020-03-02 20:16
It seems to be possible to export a static site from Sapper and to avoid server-side data fetching with conditional preloading like this:
```
<script context="module">
  export async function preload(page, session) {
    if (typeof window == 'object') {
      // load data from the (legacy/non-js) backend
    } else {
      // assign an empty array or whatever is needed to render an empty page
    }
  }
</script>
```
And triggering the client side preload on the initial page load seems to be possible by adding
```
__SAPPER__.preloaded = [];
```
to the end of src/client.js.

Does this make any sense or is there a better way to export a static site that loads data on the client only? Repeating the `typeof window` check in every preload is a bit annoying of course.

**Comment by pjebs** [comment] 2020-04-04 00:05
@markus is your code snippet for avoiding server-side data fetching OR for ditching node altogether (such as using a Go backend)?

**Comment by pjebs** [comment] 2020-04-04 00:07
I'm trying to use a Go backend and have nothing to do with node.js. Has anyone managed to achieve such a feat?

**Comment by pjebs** [comment] 2020-04-04 06:28
@Rich-Harris Is there a reason why you don't want to support non-node.js backends? Obviously Svelte is amazing. The typescript issue irritates some who consider it an adoption blocker.

Don't you think making it too opinionated may work against your project? Obviously SSR is a nice-to-have and requires node (to do conveniently), but for many projects its not a high priority. A higher priority is for those teams (that have a distinct FE and BE team) to use a different language for their backend which they are more familiar with, and arguably is superior to node.

**Comment by antony** [comment] 2020-04-04 11:33
@pjebs the maintainers team does not have the bandwidth to support alternate backends, especially ones in different languages. It isn't on the Roadmap. Please keep casual discussion to the [https://svelte.dev/chat](Discord) to avoid cluttering up issues.

**Comment by vortacio** [comment] 2020-04-07 21:18
So I'm currently learning Svelte and think it's awesome. Coming from Vue and Angular I think Svelte is just better in many ways. However, I build a lot of web apps and sometimes I need SSR and sometimes I do not. For the last year I've been using Nuxt and its been great. Thought I was going to give Sapper a try but I guess not yet. Is SPA mode forever going to be neglected in Sapper?

**Comment by antony** [comment] 2020-04-09 10:24
@vortacio Since you can build SPAs with Svelte, and there are a huge number of routers out there, adding an SPA mode to Sapper isn't very high on the priority list at the current time.

We'd happily take a PR for an SPA mode, and we're not writing it off, but there are higher priority tasks which are going to take precedence, and no amount of foot stomping is going to change that.

**Comment by benmccann** [comment] 2020-05-12 21:03
A couple cases where this might be helpful:
* testing (manual or integration)
* load shedding (if servers are getting overloaded then offload rendering to client devices)

**Comment by madacol** [comment] 2020-05-30 04:23
@Rich-Harris mentioned a workaround in https://stackoverflow.com/a/56640356/3163120

> In the meantime, you can fake it by wrapping all your markup in `{#if process.browser}` — anything inside won't be server rendered, but will be present as soon as JavaScript kicks in.

**Comment by benmccann** [comment] 2020-06-11 17:59
I actually think that this will be much more generally useful than my initial reaction was

If we implement preload headers for all the assets (https://github.com/sveltejs/sapper/issues/408) then Sapper will have a lot of smarts on the server-side even for a client-side rendered app. This is something you couldn't get from a client-side router alone and would be a complex middleware implementation leveraging the bundler. So for people that want a CSR SPA app, Sapper would provide a lot of value over other routers

And I actually think there are actually a lot of reasons a CSR app might be preferable to hydration. [There's an article from Google I highly recommend reading on this topic](https://developers.google.com/web/updates/2019/02/rendering-on-the-web). Some points:
* time-to-interactive may be worse in a hydrated application
* hydration requires sending your data to the client twice (once in the rendered HTML and once as a JSON blob to populate the initial application state)
* SSR is operationally difficult to scale. Node excels at async I/O and has the hardest time with CPU-bound operations. Rendering HTML is CPU-bound, so you're asking Node to do the thing it's worst at. This problem can be solved by running many Node processes (one per CPU core across machines) and properly load balancing between them, but it's not the simplest setup to scale
* at the current time, Svelte's hydration is a bit lacking. it actually causes the whole dom to rerender on the client. doing this rendering on both the client and server is expensive. while this is something that may be able to be improved it seems much harder than adding this option. (related tickets: https://github.com/sveltejs/svelte/issues/4975 https://github.com/sveltejs/svelte/pull/4309). hydration implementations in React and elsewhere are becoming more complex with incremental/progressive/partial hydration

**Comment by benmccann** [comment] 2020-06-15 17:12
I've sent a PR for this. The implementation was pretty close to what @Rich-Harris had suggested (it looks like the code may have changed a little since then): https://github.com/sveltejs/sapper/pull/1275

**Comment by gopherine** [comment] 2020-10-14 12:13
Not sure if this is possible in here, but is it possible to server render on something else other than, NodeJS, from what I understand currently it is not given the sapper. Middleware dependency.. However, i would love to see a pluggable mode.

The reason being, why even use NodeJS to render sapper, when the goal is to have a backend in some other language. Rather it would be much better if it's pluggable to anything programming language, be it node, go or rust and the UI should just be pluggable. 

Now it's just an idea I don't know how feasible this is to implement.

**Comment by benmccann** [comment] 2021-03-16 21:26
This will be added in SvelteKit: https://github.com/sveltejs/kit/issues/231. We won't be adding major new features to Sapper

**Closed by benmccann** 2021-03-16 21:26 UTC
Labels: proposal

**Comment by btakita** [comment] 2021-07-14 16:18
What is the recommended path to somebody wanting to maintain a Sapper app in **both** PWA & SPA mode? I cannot migrate to Svelte Kit b/c `"type": "module"` does not support `ts` files since the `js` extension is necessary for imports.

**Comment by benmccann** [comment] 2021-07-14 16:38
SvelteKit supports TypeScript out-of-the-box. I'm not quite sure what issue you're having with SvelteKit, but I'd recommend asking for support in Discord and then filing an issue with a repository that reproduces the issue if no one on Discord knows how to solve it. Sapper is not going to be receiving many if any updates

**Comment by btakita** [comment] 2021-07-14 16:46
I'm having an issue using the Typescript compiler (`tsc`), `"type": "module"` & importing `ts` module from another `ts` module. The following error occurs.

`Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...' imported from ...`

I'll ask again on Discord.

**Comment by btakita** [comment] 2021-07-16 04:36
I dropped a couple of days into the migration & sadly, it doesn't look like `@sveltejs/adapter-static` will be able to bundle a SPA to run from `file://` nor is there the will to make it work this way. I'm probably best off rolling my own solution at this point.

**Comment by btakita** [comment] 2021-07-18 23:54
@benmccann Are there any recommended alternatives to svelte-kit migrate from Sapper? I'm unfortunately running into many weird issues & running out of time to do the migration. I need an SPA using hash routing & the `file://` protocol. Thanks.

**Comment by btakita** [comment] 2021-07-18 23:58
@benmccann I've been working on migrating to sveltekit & even found some bugs. I'm afraid that it's not ready to migrate to for my project, mainly due to vite's lack of SSR support & issues over converting to `"type": "module"`. In the meantime, I need to have a SPA output for my sapper app to serve using `file://` & hash urls. Perhaps I should fork Sapper to add SPA support or use routify in the meantime?
