### ISSUE TITLE
segment is undefined client side on error page

### ISSUE THREAD

**Issue by nikse** [sveltejs/sapper#1343] opened 2020-07-27 17:20 UTC
**Describe the bug**

The segment variable is undefined on client side (defined on server side)  in the _layout.svelte file when rendering the _error.svelte file

**Logs**
Please include browser console and server logs around the time this bug occurred.

**To Reproduce**
To help us help you, if you've found a bug please consider the following:

Run sapper starter template and navigate to `/a` with the following code in _layout.svelte

```
export let segment;
console.log(segment) // ssr: "a", client: undefined
```

* If possible, we recommend creating a small repo that illustrates the problem.
* Reproductions should be small, self-contained, correct examples – http://sscce.org.

Occasionally, this won't be possible, and that's fine – we still appreciate you raising the issue. But please understand that Svelte is run by unpaid volunteers in their free time, and issues that follow these instructions will get fixed faster.

**Expected behavior**

Client side segment should have the same value as the server side

**Stacktraces**
If you have a stack trace to include, we recommend putting inside a `<details>` block for the sake of the thread's readability:

<details>
  <summary>Stack trace</summary>

  Stack trace goes here...
</details>

**Information about your Sapper Installation:**
- Your browser and the version: (e.x. Chrome 52.1, Firefox 48.0, IE 10)

- Your operating system: (e.x. OS X 10, Ubuntu Linux 19.10, Windows XP, etc)

- Your hosting environment: (i.e. Local, GCP, AWS, Now, etc...)

- Sapper version (Please check you can reproduce the issue with the latest release!)

- Svelte version (Please check you can reproduce the issue with the latest release!)

- If it is an exported (npm run export) or dynamic application.

- Whether your application uses Webpack or Rollup

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

Note: the more honest and specific you are here the more we will take you seriously.

**Additional context**

**Comment by Conduitry** [comment] 2020-07-27 17:34
Approximately a duplicate of #948 and a few other related issues.

**Closed by Conduitry** 2020-07-27 17:34 UTC
