### ISSUE TITLE
export hangs forever with webpack 

### ISSUE THREAD

**Issue by michalvankodev** [sveltejs/sapper#800] opened 2019-07-12 09:13 UTC
Hi I've just started to use sapper for a static site.

I tried the sapper template with webpack and I got into ugly situation where the `npm run export` command will hang and never exit.

It doesn't happen with the rollup setup so I will continue to use that one.

**Comment by benmccann** [comment] 2020-08-28 21:45
I'm going to close this issue because there's not enough details as to how to reproduce. Please feel free to reopen with more details

**Closed by benmccann** 2020-08-28 21:45 UTC
Labels: export, pending clarification
