### ISSUE TITLE
Rollup watch not reloading on change

### ISSUE THREAD

**Issue by ilicmarko** [sveltejs/sapper#617] opened 2019-03-26 10:52 UTC
I am really having an unpleasing experience using Sapper. Because the watch mode isn't working, or kind of works (sometimes)...

I am using `Rollup` and when I run `yarn run dev` it goes into the watch mode... I make a few CSS changes and it works, but I make a JS or HTML change it won't reload any more.

I have to quit the process and run the `dev` again.

Here is the console output:

```
✔ service worker (28ms)
> Listening on http://localhost:3001

src/components/Editor.html changed. rebuilding...
// Here it worked, successful reload

src/components/Editor.html changed. rebuilding...
✔ client (429ms)
✔ server (440ms)
✔ service worker (17ms)
// From now on it doesn't work anymore...
```

I am using the example from the docs page.

OS `Ubuntu 18.04`
Yarn: `1.15.2`
Node: `v11.9.0`

**Comment by lafriakh** [comment] 2019-08-22 20:42
I have the same issue here.
Is there any solution for it.

I'm using `debian 10`

**Comment by paco3346** [comment] 2019-09-27 23:33
I too experience this issue.

There's a discussion [here](https://github.com/rollup/rollup/issues/1666) and [here](https://github.com/sveltejs/template/issues/29) about disabling chokadir on Linux.

Sapper itself [now uses cheap-watch](https://github.com/sveltejs/sapper/pull/365/commits/f9bf23dc430e9fc65bfe46fce19209abff582fa9) but a fresh install of sapper-template has neither.

This issue persists across 8.16.1, 10.16.0, and 12.10.0.

**Comment by paco3346** [comment] 2019-09-28 18:41
Further investigation reveals that the latest build of sapper uses a [baked in copy](https://github.com/sveltejs/sapper/blob/830dd27997ddde47f127a074125014be9555f260/src/api/dev.ts) of cheap-watch so it doesn't show up in the dependencies.

Unfortunately since this depends on fs.watch [which cannot detect safe] writes(https://github.com/nodejs/node-v0.x-archive/issues/3172) there's no fix if your underlying issue is caused by safe writes. You'd either need to use a different library such as chokidar (which uses a different mechanism for watching under the hood) or disable safe writes in your editor.

**Comment by paco3346** [comment] 2019-09-28 21:38
I've posted my final conclusions here https://github.com/rollup/rollup/issues/1666#issuecomment-536227450

**Comment by paco3346** [comment] 2019-09-30 18:11
I've done some more work on this and have discovered a working solution.  See https://github.com/rollup/rollup/issues/2988

Note that this particular solution depends on chokidar. (And subsequently configuring rollup to use that instead of vanilla fs.watch)

**Comment by antony** [comment] 2020-05-13 15:51
I think this was closed by https://github.com/rollup/rollup/issues/2988 so closing here too

**Closed by antony** 2020-05-13 15:51 UTC
Labels: pending clarification
