### ISSUE TITLE
How to make a validation alert before navigating to another page ?

### ISSUE THREAD

**Issue by nemixe** [sveltejs/sapper#1035] opened 2019-12-25 20:10 UTC
i've been looking for something like beforeDestroy to create validation when user has not fill the form completely and they want to navigate to another page they should receive alert like "are you sure want to discard your changes ?", is there any possible way to create that validation on sapper ?

**Comment by 0xsven** [comment] 2020-01-02 14:23
Have a look at the answer in this issue: https://github.com/sveltejs/sapper/issues/1040

**Comment by antony** [comment] 2020-01-03 12:01
This is a question, and a duplicate of #1040 as mentioned by 0xsven. Please ask questions in the [discord](https://svelte.dev/chat)

**Closed by antony** 2020-01-03 12:01 UTC
Labels: question
