### ISSUE TITLE
More global route hooks

### ISSUE THREAD

**Issue by UltraCakeBakery** [sveltejs/sapper#1457] opened 2020-08-30 11:30 UTC
**Is your feature request related to a problem? Please describe.**
I see this question on discord every day. There are also issues here on github that have been closed while they should've stayed open.

I want on/before/after route enter/leave hooks that I can add on routes and layouts.

**Describe alternatives you've considered**
Listening to store changes https://sapper.svelte.dev/docs/#Stores isn't gonna be enough since there are huge delays between the page navigation starting, loading to be finished, being add to the dom and actually get rendered. 

**How important is this feature to EVERYONE ASKING THIS EVERY DAY?**
A lot. This will make it easier for everyone to transition from other frameworks like Vue and React to Svelte, and make our sapper codebases considerably smaller in the long run.

**Comment by benmccann** [comment] 2020-08-30 15:45
I'm going to close this as a duplicate of https://github.com/sveltejs/sapper/issues/1278 where we've discussed adding such hooks

**Closed by benmccann** 2020-08-30 15:45 UTC
