### ISSUE TITLE
MiniCssExtractPlugin not working anymore on webpack after 0.28.1

### ISSUE THREAD

**Issue by monkeythedev** [sveltejs/sapper#1454] opened 2020-08-29 03:05 UTC
#1415 This change broke MiniCssExtractPlugin on webpack.

CSS files are not included anymore in the resulting html.

**Comment by benmccann** [comment] 2020-08-29 03:37
This is probably a duplicate of https://github.com/sveltejs/sapper/issues/1446

**Comment by benmccann** [comment] 2020-08-30 15:41
Can you test with 0.28.3? It has a bunch of CSS fixes in it

**Comment by monkeythedev** [comment] 2020-08-30 18:28
> Can you test with 0.28.3? It has a bunch of CSS fixes in it

Just tried, unfortunately it's still not working. CSS files is created under dev/client but it's not imported in the generated html.

It works with 0.28.0 though,

This is what i'm working on if it could be of any help: https://github.com/monkeythedev/svelte-material-ui/tree/typescript_4%2Bmaterial_7/site

**Comment by benmccann** [comment] 2020-08-30 21:28
Thanks. Sharing that was helpful and allowed me to reproduce. I sent a fix here: https://github.com/sveltejs/sapper/pull/1461

**Closed** 2020-09-01 15:44 UTC
Labels: bundling
