### ISSUE TITLE
importing svelte components via index.js results in errors on svelte syntax

### ISSUE THREAD

**Issue by heardy** [sveltejs/sapper#288] opened 2018-06-22 04:12 UTC
I'm not sure whether this is an issue with `sapper` or `svelte-loader`. I have come across an issue with importing svelte components from a node module main/index file.

The issue i am getting is the the svelte component from the node module is being imported but error'ing on svelte syntax. It looks like the svelte component is not being picked up by webpack or svelte-loader?

If i load the svelte component directly, not via an index file, then it works fine

So to clarify `import Foo from 'some-module/src/Foo.html'` will work.

`import { Foo } from 'some-module'` will error (see below) on svelte syntax as Foo.html has not been compiled.

I have created a simple test sapper app as well as simple svelte module to demonstrate the problem.

https://github.com/heardy/sapper-test-app - this contains the 2 example import methods (https://github.com/heardy/sapper-test-app/blob/master/routes/index.html#L51)

https://github.com/heardy/svelte-module-test - contains Foo.html svelte component and index.js used to access `Foo.html`.

<img width="607" alt="screen shot 2018-06-22 at 14 03 41" src="https://user-images.githubusercontent.com/678392/41757389-3477c5e0-7625-11e8-86c1-e96190f931f3.png">

**Comment by heardy** [comment] 2018-06-25 01:02
Tried with svelte template which is using rollup and it works as expected - https://github.com/heardy/svelte-test-app-rollup

**Comment by heardy** [comment] 2018-06-26 01:46
Tried with standalone svelte and webpack build (no sapper) and still doesn't work - https://github.com/heardy/svelte-test-app-webpack

So guess this not a sapper issue?

**Comment by Rich-Harris** [comment] 2018-06-28 18:17
The issue is that svelte-module-test is a CommonJS module that imports an ES module. Replace `svelte-module-test/index.js` with this code and everything will work:

```diff
-const Foo = require('./Foo.html');
+import Foo from './Foo.html';

-module.exports = {
+export {
    Foo
} 
```

Closing as this isn't an issue with Svelte or Sapper (or svelte-loader)

**Closed by Rich-Harris** 2018-06-28 18:17 UTC

**Comment by heardy** [comment] 2018-06-28 23:40
Thanks Rich. I should have mentioned that's what I originally used. I have updated `svelte-module-test/index.js` to export ES module.

This is the error i get when using ES module:

<img width="561" alt="screen shot 2018-06-29 at 9 25 51 am" src="https://user-images.githubusercontent.com/678392/42065489-7e0b1276-7b7e-11e8-94fd-52b772115aff.png">
