### ISSUE TITLE
CSS for index route in wrong chunk

### ISSUE THREAD

**Issue by sfriedel** [sveltejs/sapper#1492] opened 2020-09-07 14:55 UTC
**Describe the bug**
There seems to be an edge case in the dependency tracking which leads to a route lacking inclusion of it's CSS. I haven't exactly isolated the trigger conditions but the following seem to influence it:

* index and at least 1 other route must import and use a shared dependency js file
* one route must import and use something from `index.svelte` (either the component or anything else exported in `<script context="module">`)

What in some combinations of the above will happen is that there will be no `dependencies: {'index.svelte: ...}` entry in `build.json`, e.g.

```
  "dependencies": {
    "about.svelte": [
      "about.6b7a7083.js"
    ],
    "other.svelte": [
      "other.1ace7670.js",
      "index.2ef1e205.js",
      "assets/index-2c976220.css"
    ]
  }
```

from the example repo below.

**To Reproduce**
https://github.com/sfriedel/sapper-bug-repro/tree/missing-index-css (`missing-index-css` branch) based on sapper-template repo

* Go to http://localhost:3000/
* verify that the h2 `This is not visible when index.svelte CSS was loaded correctly!` is visible
* verify that no `index.[hash].css` file gets loaded
* Go to http://localhost:3000/other
* verify that the h2 `This is not visible when index.svelte CSS was loaded correctly!` is not visible
* verify that the `index.[hash].css` file gets loaded

**Expected behavior**
On both routes the `index.[hash].css` should be loaded.

**Information about your Sapper Installation:**

```
 System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 2.99 GB / 15.34 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - /usr/bin/npm
    Watchman: 4.9.0 - /home/sef/.local/opt/watchman/bin/watchman
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0.1
  npmPackages:
    rollup: ^2.3.4 => 2.26.10
    sapper: ^0.28.0 => 0.28.5
    svelte: ^3.17.3 => 3.24.1
```

**Severity**
Currently this prevents me from deleting a single route file in a project because doing so will trigger this edge case and index.svelte styles would be gone.

**Additional context**
I tried tracing it a bit and added some logging to the filter in `RollupCompiler.ts : get_route_entry_chunks`. Those specific conditions seem to cause `facadeModuleId` for `index.[hash].js` to be `null` like this:

```js
{
  fileName: 'index.9e5abb07.js',
  dynamicImport: true,
  facadeModuleId: null
}
```

and due to this, it gets filtered out. At that point I had to give up because I don't know nearly enough about the rollup internals to figure out why `facadeModuleId` would be null in those cases. Hopefully the repo above will help to figure this out.

**Comment by benmccann** [comment] 2020-09-07 20:31
Hmm, yeah, this seems like possibly a bug in Rollup. I'm not why why `facadeModuleId` is `null`. We should file a bug with them. The tricky thing will be seeing if we can reproduce it in a project without Sapper

**Comment by benmccann** [comment] 2020-09-08 22:14
@sfriedel would you be able to file a bug with Rollup about this one?

**Comment by sfriedel** [comment] 2020-09-09 08:07
@benmccann I can try to do that. Not sure if I'll manage to fabricate an isolated reproduction case for rollup though.

Also I was looking at the rollup documentation for a bit and noticed that a `null` in `facadeModuleId` might actually be valid/documented behavior:

```
      //   facadeModuleId: string | null, // the id of a module that this chunk corresponds to
```

Couldn't find under which conditions this is supposed to happen though

**Comment by babeard** [comment] 2020-09-09 17:51
I was seeing the same problem. Updating sapper to 0.28.6 fixes this issue for me.

See https://github.com/sveltejs/sapper/pull/1494

**Comment by benmccann** [comment] 2020-09-09 18:10
I am surprised that fixes it. We may have just gotten lucky that the graph is navigated in a different order. Still I will go ahead and close this for now since the reproduction no longer fails. If you run into another problem, please feel free to file an issue with a new reproduction

**Comment by babeard** [comment] 2020-09-09 18:52
Sorry, it seems like I didn't verify thoroughly enough. 

The behavior is indeed fixed but not in a way that was expected. It now appears the required css was not included in `index.[hash].css` but rather stuffed into `client-[hash].css` in 0.28.6. In 0.28.5, the css is missing altogether.

I'm not sure this warrants re-opening the issue as the end result is that the css is indeed included, just not in the expected chunk.

**Comment by benmccann** [comment] 2020-09-09 19:22
Hmm, yeah, that's not expected although better. It should be in `index.[hash].css`, but this seems to be due to the Rollup issue, which we'll need someone to report over at that repo

**Comment by benmccann** [comment] 2020-09-09 23:27
I filed https://github.com/rollup/rollup/issues/3772 to ask if my understanding of the intended usage of `facadeModuleId` was correct. I don't have a minimal reproduction yet though, so that would still be helpful to share there if you're able to reproduce without Sapper

**Comment by sfriedel** [comment] 2020-09-10 08:09
@benmccann due to some work deadlines I probably won't manage to work on the isolated reproduction case before the weekend, sorry.
What I can confirm though is that even with the latest changes in sapper 0.28.6 the underlying issue is still present, though it can't be observed with the index CSS any more because it's all bundled in the `client.[hash].css`.

New reproduction steps:

* Checkout https://github.com/sfriedel/sapper-bug-repro/tree/missing-index-css
* yarn install && yarn dev
* Open `__sapper__/dev/build.json`

Actual behavior: there is no `index.svelte` entry in `depenencies`

Expected behavior: the following `dependencies` entry should be present: 

```
  "dependencies": {
    "index.svelte": [
      "index.[hash].js"
    ],
```

**Comment by sfriedel** [comment] 2020-09-13 11:42
@benmccann not sure if you still need it since you closed the rollup issue but I've managed to create a minimal reproduction case based on the `rollup/rollup-starter-app` repo updated to rollup 2.26.11

* Checkout https://github.com/sfriedel/rollup-bug-repro/tree/null-fascademoduleid (branch `null-fascademoduleid`)
* yarn install && yarn build

You should see the following output:
```
$ rollup -c

src/main.js → dist...
Rendering chunk main.08a4689b.js with facadeModuleId /home/sef/Development/rollup-repro/src/main.js
Rendering chunk route-a.daa42ab3.js with facadeModuleId null
Rendering chunk route-b.8275ca2d.js with facadeModuleId /home/sef/Development/rollup-repro/src/route-b.js
created dist in 191ms
Done in 0.41s.
```

**Comment by benmccann** [comment] 2020-09-13 13:02
Awesome. thanks!

**Closed** 2020-09-15 20:36 UTC
Labels: bug, bundling

**Comment by sfriedel** [comment] 2020-09-16 10:59
@benmccann Just wanted to confirm that 0.28.7 fixed this issue in all projects and testcases where I was seeing it before. Thank you very much :smile:
