### ISSUE TITLE
This warning keeps upsetting me, is there any way to delete it?

### ISSUE THREAD

**Issue by voorjaar** [sveltejs/sapper#1600] opened 2020-10-13 02:27 UTC
**Bug Description**

In dev mode if add _layout.svelte inside a folder there is a warning at console if I access root path:
<Routes> was created with unknown prop 'segment'
<Routes> received an unexpected slot "default".
Other pages also have this issue if not define a _layout.svelte.

**Comment by benmccann** [comment] 2020-10-13 02:47
Closing as duplicate of https://github.com/sveltejs/sapper/issues/824

**Closed by benmccann** 2020-10-13 02:47 UTC
