### ISSUE TITLE
rollup-plugin-postcss not working

### ISSUE THREAD

**Issue by JoelEllis** [sveltejs/sapper#699] opened 2019-05-18 10:53 UTC
I can't seem to get postcss to work properly and extract my css like it does in pure svelte.
With css extract option on it generates: 
```js
export default undefined;
export default undefined;
/* sourceMappingURL=./chunk.e3537e20.css.map */
```
but with it off, it generates:
```js
var css = "a.link.svelte-131civd{color:#d3d3d3}";
export default css;
import styleInject from 'C:/Users/admin/Code/domainhax/node_modules/style-inject/dist/style-inject.es.js';
styleInject(css);
var css = "main.svelte-1joomdn{padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;width:64em}input.svelte-1joomdn{width:100%}#description.svelte-1joomdn>div.svelte-1joomdn{width:50%;padding:0;float:left}header.svelte-1joomdn{text-align:center}p.svelte-1joomdn{margin-top:0}a.svelte-1joomdn{color:#959595}h1.svelte-1joomdn a.svelte-1joomdn{color:#dfdfdf}";
export default css;
import styleInject from 'C:/Users/admin/Code/domainhax/node_modules/style-inject/dist/style-inject.es.js';
styleInject(css);
/* sourceMappingURL=./chunk.e3537e20.css.map */
```

In normal svelte when I do `import './global.css'`, it generates a inlined bit of js with it off, and the processed file with it on, and does the same for svelte's generated CSS.
I can't figure out what's going wrong, but I would like my css minified and prefixed.

**Comment by MaxMilton** [comment] 2019-05-18 22:34
You need to give a bit more context for someone to understand your use case.

1. What version of Svelte and Sapper?
1. Which build tool, Webpack or Rollup?
1. Are you trying to import that CSS file in a component or in a JS file?
1. Are you using a Svelte preprocessor?
1. How have you configured PostCSS?
1. Are there any errors in your console?
1. etc.

**Comment by derpmarine168** [comment] 2019-05-19 13:44
1. This is sapper 0.26 with svelte 3.
2. Rollup
3. The CSS is both the css generated by svelte from the components and imported css, aka all the css that passes through rollup.
4. No.
5. postcss.config.js:
    ```js
    module.exports = {
      extract: true,
      sourceMap: false,
      plugins: [
        require('@csstools/postcss-sass')(/* node-sass options */),
        require("postcss-import"),
        require("postcss-preset-env")({ stage: 4 }),
        require("autoprefixer")(),
        require("postcss-csso")
      ],
      parser: 'postcss-scss',
    }
    ```
    General standard across my projects.
6. No - it's silent apart from babel telling me to specify `core-js` version

**Comment by MaxMilton** [comment] 2019-05-19 21:11
To process PostCSS in Svelte `<style>` blocks you need to set up a preprocessor such as <https://github.com/TehShrike/svelte-preprocess-postcss> or <https://github.com/kaisermann/svelte-preprocess>.

To process PostCSS imported in JS files you need to use a Rollup plugin such as <https://github.com/egoist/rollup-plugin-postcss>. Sapper will take care of emitting the CSS assets but you do need to process it first. The order of your Rollup plugins can also be important.

**Comment by derpmarine168** [comment] 2019-05-24 19:26
@MaxMilton As far as i'm aware, Svelte outputs the CSS file(s) to rollup, for rollup-plugin-postcss to take care of.  This works fine with svelte by itself, but *not with sapper*!
That's what I'm trying to say here, is sapper is somehow forcing the CSS files to be JS.

**Comment by MaxMilton** [comment] 2019-05-26 02:38
Svelte first parses the CSS with `css-tree` in order to find any unused CSS selectors. Because of this the styles inside any `<style>` block _must_ be valid CSS. Only then does it pass the styles through.

If you want your `<style>` blocks processed with PostCSS you need to use a preprocessor. See [this comment for an example with SASS](https://github.com/sveltejs/sapper/issues/123#issuecomment-495825536) — the same thing applies using a PostCSS preprocessor.

**Comment by JoelEllis** [comment] 2019-05-28 19:40
Sorry - It's my config causing the issue - I have no idea what about it though! But i've got it working fine in anothjer project. 

Quick side note - sapper seems to not work in Git Bash - if you run it in a fresh repo, it give some kind of error about can't find undefined\client.js. Possibly to do with git bash pollyfilling windows paths so \ is an escape charrracterr rather than the path seperator in git bash?

**Comment by JoelEllis** [comment] 2019-05-28 20:01
I made a repo to demonstrate my issue. https://github.com/JoelEllis/sapper-postcss-issue

Quick side note - sapper seems to not work in Git Bash - if you run it in a fresh repo, it give some kind of error about can't find undefined\client.js. Possibly to do with git bash pollyfilling windows paths so \ is an escape charrracterr rather than the path seperator in git bash?

**Comment by dephiros** [comment] 2019-06-02 20:16
I run into this issues as well.
What I am trying to do is to use the preprocessor to process svelte css
Use rollup-plugin-postcss to process css imported by js
Maybe if there is a way to make rollup-plugin-postcss ignore files emitted by svelte

**Comment by JoelEllis** [comment] 2019-07-14 13:49
@dephiros That works great. Thanks.
TBH, this seems really unintuitive though - what makes it behave like this? @MaxMilton

**Comment by JoelEllis** [comment] 2019-07-31 17:42
In some of my projects it doesn't work though. I'm working around that by removing psotcss form the build, getting sapper to output css seperately and running `postcss __sapper__/build/client/**/*.css --dir __sapper__/build/client --base __sapper__/build/client`.

**Comment by nhristov** [comment] 2020-03-23 20:41
This is based on the official template https://github.com/nhristov/sapper-template-rollup/tree/postcss-tailwind-purgecss. It adds postcss, purgecss, cssnano and tailwindcss without having to modify the build script in your package.json

**Comment by JoelEllis** [comment] 2020-03-27 15:55
Just reposting here what I replied to @nhristov's email with:

It seems to work great (excluding that it doesn't minify global.css, but that can be fixed by importing it in the JS rather than the HTML IIRC).

Just to note now, I'm not really in the same environment as I was when I made that issue - I used to be on windows (10 home), I've moved to a Linux system full-time now.
I went back and tested the repo I made for the bug and it does seem to have similar/the same behaviour as before, with the same configurations being broken.

**Comment by JoelEllis** [comment] 2020-03-27 16:20
After some testing, I figured out how the repo works, and it seems a bit weird to have a ganerated & minifed style comitted to git?

**Comment by JoelEllis** [comment] 2020-03-27 16:32
Dispite this solving my problem, I don't think this really solves the bug (or incompatibility). It's a workaround, in my opinion. The issue is what causes the incompatibility with postcss, and hwo dow we fix it without requiring a non-obvious workaround. This could be a bug in rollup, but I've only seen it occur with sapper.

If this is going to be a `WONTFIX` bug, can we get it documented?

**Comment by antony** [comment] 2020-03-27 16:58
@JoelEllis I'm struggling to determine from this reading issue, because it's not clear:

* What is the bug that you're having trouble with
* What is the workaround you are using
* What is the proposed solution (a documentation update, perhaps?)

Regarding the third point - from what I can ascertain, your problem stems from using postCSS in Sapper. Sapper doesn't natively support PostCSS, so we wouldn't necessarily document a solution for PostCSS in the main Sapper docs.

If this is a problem with Rollup then we can raise the issue / fix the issue there.

Also I notice your reproduction is archived. Do you have a new, simplified reproduction so that we can see the issue for ourselves?

Thanks!

**Comment by JoelEllis** [comment] 2020-03-27 17:38
Hey!
The bug I'm encountering is when svelte is configured with sapper with `emitCSS: true`, when put through postCSS the CSS is either converted to CSS with a javascript wrapper whilst still being lodaed as a stylesheet, or being a file of `export default undefined`. With emitCSS false, I don't think it goes through PostCSS at all. This is demonstrated in the original repo, and I've made branches with a few of the configurations. I archived it as this issue hadn't seen activity in a long time.

The work around I'm using/have been given is https://github.com/nhristov/sapper-template-rollup - use PostCSS as a preprocessor for css inline in svelte, use PostCSS's rollup plugin to minify external CSS files (imported in server.js). This isn't ideal as CSS imported in client.js is not processed and the CSS from sapper is not processed as a whole, meaning minifers can't work at their full potential and there are newlines left in the files. However, it's good enough.

My ideal solution is to make situations 1 & 2 output valid CSS, or to document the workaround, @nhristov told me to document their workaround by making a question/answer on stackoverflow.

**Comment by JoelEllis** [comment] 2020-03-27 17:44
In situation 1, main.css is outputted as:
![image](https://user-images.githubusercontent.com/28905212/77784356-4a09b200-7052-11ea-929b-ea3af8a65b9a.png)
and the page renders as:
![image](https://user-images.githubusercontent.com/28905212/77784384-568e0a80-7052-11ea-9742-5ca8916c8a8c.png)
In situation 2, main.css is ouputted as:
![image](https://user-images.githubusercontent.com/28905212/77784471-7a515080-7052-11ea-88fd-b8fd95948556.png)
and it renders the same.
3 and 4, from what I can tell, don't get processed by postcss as the CSS is embedded in the javascript.

**Comment by antony** [comment] 2020-03-30 16:55
I can't determine that there is an actual issue with Sapper from this ticket, so closing. Feel free to re-open if you can isolate/point at an exact issue with Sapper itself.

**Comment by krzysztof-grzybek** [comment] 2020-06-11 07:17
@antony I think I know why this bug occurs.

1. We collect css files for bundle on the `transform` rollup hook ([here](https://github.com/sveltejs/sapper/blob/master/src/core/create_compilers/RollupCompiler.ts#L43)).
2. `rollup-plugin-postcss` emit new files for bundle on the `generateBundle` rollup hook ([here](https://github.com/egoist/rollup-plugin-postcss/blob/v2.8.2/src/index.js#L216)).


Therefore, postcss plugin emits files after we collect files for bundle. It seems also, that emitting file during `generateBundle` is a [valid case](https://rollupjs.org/guide/en/#generatebundle). I'm new to svelte/rollup ecosystem, so correct me if I'm wrong, but I think that we should collect css files on `writeBundle` rollup hook.

Note, that this is probably this is only the part of the problem.

**Comment by benmccann** [comment] 2020-06-11 12:24
Thanks for the excellent investigation @krzysztof-grzybek! It sounds like this bug should probably be reopened.

**Comment by Evertt** [comment] 2020-07-09 11:35
Is there a workaround for now? Because I'd *really* like to be able to use this soon.

**Comment by krzysztof-grzybek** [comment] 2020-07-09 11:55
I used @dephiros workaround.

**Comment by Evertt** [comment] 2020-07-09 12:06
That doesn't work for me. I did find out how to fix the bug mostly. I'm gonna submit a very bad PR in a few minutes, hoping that other people are willing to improve it so that it can be merged.

**Comment by benmccann** [comment] 2020-07-09 21:59
There's a template that @babichjacob has provided at https://github.com/babichjacob/sapper-postcss-template. As far as I know, he hasn't hit this issue (feel free to correct me @babichjacob). Would using his setup work for you all? I'd be curious to know if it has some issue or if it only happens when some other setting is present

**Comment by dimfeld** [comment] 2020-07-09 22:18
It's been a while since I tried it, but IIRC the problem appears when using `emitCss: true,` in the rollup config.

**Comment by babichjacob** [comment] 2020-07-09 22:21
We don't have this issue because we don't import CSS-like files in JS. We also don't use `emitCss`.

`svelte-preprocess` takes care of it (and `rollup-plugin-postcss` isn't involved at all). The nearest equivalent of `import ./styles.css` is probably
```html
<style lang="postcss"> <!-- possibly with global -->
  @import "./styles.css";
</style>
```
with `postcss-import` as a PostCSS plugin.
(This doesn't work outside Svelte files, but I'm not sure why it would be needed for that not to be the case).

**Comment by Evertt** [comment] 2020-07-09 22:24
Ah yes I see that it does work if I import the css in a `<style>` tag instead of in a `<script>` tag.

**Comment by babichjacob** [comment] 2020-07-10 02:52
> We also don't use `emitCss`.

Oh no, I said this off of memory and was wrong. We actually do have [`emitCss: true`](https://github.com/babichjacob/sapper-postcss-template/blob/master/rollup.config.js#L36) for the client, but not the server. (I felt this warranted its own reply to update everyone who needed to know).

**Comment by benmccann** [comment] 2020-07-10 05:07
Ah, so this bug seems to me to really be specific to `rollup-plugin-postcss` and not PostCSS in general

It sounds to me like `rollup-plugin-postcss` creates JavaScript to inject the script into the `head` element:
```
function __$styleInject(css) {
  css = css || '';
  var head = document.head || document.getElementsByTagName('head')[0];
  var style = document.createElement('style');
  style.type = 'text/css';
  if (style.styleSheet){
    style.styleSheet.cssText = css;
  } else {
    style.appendChild(document.createTextNode(css));
  }
  head.appendChild(style);
}
__$styleInject("/* Styles omitted for brevity... */");
```

And Sapper isn't setup to expect transforming CSS into a mix of JS and CSS

This aligns with @krzysztof-grzybek's description of the issue https://github.com/sveltejs/sapper/issues/699#issuecomment-642460603

**Comment by lmf-git** [comment] 2020-09-12 20:04
@krzysztof-grzybek nice work!!

**Comment by csaltos** [comment] 2020-09-18 12:32
Just in case here a reference using Sapper with PostCSS fixed -> https://dev.to/csaltos/sapper-with-material-ui-35id (it uses SMUI as a bonus)

**Comment by lehno** [comment] 2020-09-25 18:47
Thanks @csaltos

**Comment by benmccann** [comment] 2020-12-10 22:31
I would recommend using the `postcss` option with [`svelte-preprocess`](https://github.com/sveltejs/svelte-preprocess) instead of using `rollup-plugin-postcss`. I'm going to close this since that seems to be a working path forward for most people. If anyone has a use case that solution doesn't address, please share it here and we can consider how best to solve your issue and whether `rollup-plugin-postcss` support is necessary

**Closed by benmccann** 2020-12-10 22:31 UTC
Labels: bundling

**Comment by benbabics** [comment] 2021-10-04 18:04
> I would recommend using the `postcss` option with [`svelte-preprocess`](https://github.com/sveltejs/svelte-preprocess) instead of using `rollup-plugin-postcss`. I'm going to close this since that seems to be a working path forward for most people. If anyone has a use case that solution doesn't address, please share it here and we can consider how best to solve your issue and whether `rollup-plugin-postcss` support is necessary

What exactly does that look like for those of us struggling with this that aren't familiar with bundler configurations.

```
preprocess: sveltePreprocess({
  sourceMap: !production,
  postcss: {
    plugins: [ 
      require('autoprefixer')(),
      // do something here?
    ]
  }
}),
```

**Comment by benmccann** [comment] 2021-10-04 18:14
I would recommend switching to SvelteKit. Then you can simply run `npx svelte-add@latest postcss`: https://github.com/svelte-add/postcss
