### ISSUE TITLE
Preload with TypeScript not working

### ISSUE THREAD

**Issue by daarxwalker** [sveltejs/sapper#1312] opened 2020-07-10 14:30 UTC
**Describe the bug**
Preload with using TypeScript not working

**Logs**
index.svelte:9 <Blog> was created without expected prop 'data'

**To Reproduce**
Not working
![Snímek obrazovky 2020-07-10 v 16 25 39](https://user-images.githubusercontent.com/26570413/87165125-00279d80-c2ca-11ea-8a5c-f2bace52492d.png)

Working
![Snímek obrazovky 2020-07-10 v 16 26 01](https://user-images.githubusercontent.com/26570413/87165163-0ddd2300-c2ca-11ea-8720-9ccbed5bb4f1.png)

**Expected behavior**
Should work same with TypeScript

**Information about your Sapper Installation:**
- Your browser and the version: Chrome latest

- Your operating system: macOS Catalina 10.15.5

- Your hosting environment: Local

- Sapper version: 0.27.16

- Svelte version: 3.24.0

- Rollup

**Severity**
Can't preload if svelte component using TypeScript

**Additional context**
https://github.com/sveltejs/sapper/issues/1241
Found this, but it's closed and no solution.

**Comment by Conduitry** [comment] 2020-07-10 14:38
Duplicate of #760.

**Closed by Conduitry** 2020-07-10 14:38 UTC
