### ISSUE TITLE
When building lists in loop, closing </li> tags are missing after build and export in html files.

### ISSUE THREAD

**Issue by floratmin** [sveltejs/sapper#1061] opened 2020-01-18 18:40 UTC
**Describe the bug**
When building list with looping over array, the closing </li> tags are missing on all list entries except the last one.

**Logs**
No failure or warning during build reported.

**To Reproduce**
```
<script>
    const dbMenu = [
        {
            name: 'One',
         },
        {
            name: 'Two'
        },
        {
            name: 'Three'
        }
    ]
</script>
<nav>
    <ul>
      {#each dbMenu as menu}
        <li>
            <a href=".">{menu.name}</a>
        </li>
      {/each}
    </ul>
</nav>
```

When i build and export the menu the html file misses closing tags `</li>` on some entries:

   ```
 <nav>
        <ul>
            <li><a href=.>One</a>
            <li><a href=.>Two</a>
            <li><a href=.>Three</a></li>
        </ul>
    </nav>
```

I tried this on a fresh install of sapper with the same outcome. Somehow all except the last closing tag are missing.

**Expected behavior**
HTML should be valid.

**Information about your Sapper Installation:**

Ubuntu 18.04

- Sapper version (Please check you can reproduce the issue with the latest release!)
  "dependencies": {
    "compression": "^1.7.1",
    "polka": "next",
    "sirv": "^0.4.0"
  },
  "devDependencies": {
    "npm-run-all": "^4.1.5",
    "sapper": "^0.27.0",
    "svelte": "^3.0.0",
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.0.0",
    "@babel/plugin-transform-runtime": "^7.0.0",
    "@babel/preset-env": "^7.0.0",
    "@babel/runtime": "^7.0.0",
    "@rollup/plugin-commonjs": "^11.0.0",
    "@rollup/plugin-node-resolve": "^6.0.0",
    "@rollup/plugin-replace": "^2.2.0",
    "rollup": "^1.20.0",
    "rollup-plugin-babel": "^4.0.2",
    "rollup-plugin-svelte": "^5.0.1",
    "rollup-plugin-terser": "^4.0.4"
  }

- If it is an exported (npm run export) or dynamic application.
exported html file (npm run build and then export).
- Whether your application uses Webpack or Rollup
Same error in Webpack and Rollup.

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of Sapper entirely?

Makes usage of sapper impossible, because i can not build dynamic menus.

**Comment by Conduitry** [comment] 2020-01-18 19:04
This isn't a bug, it's the result of running the HTML through a minifier during export. Starting a new `<li>` without closing the previous one is valid HTML, and implicitly closes the last one. https://html.spec.whatwg.org/dev/syntax.html#syntax-tag-omission

**Closed by Conduitry** 2020-01-18 19:04 UTC

**Comment by floratmin** [comment] 2020-01-19 13:09
Thank you, i didn't know about these optimizations. But then this optimization is not applied to the index.html page of the blog in the sample installation.

Also i saw that changes of the main.css in the static folder have no effect in the dev or build mode. Changes are only visible in export mode. Should I open a seperate ticket for this?

**Comment by AlexFeier** [comment] 2020-09-16 11:55
I know this is not a BUG but I really need a way to configure these values inside my project!

        emoveAttributeQuotes: false
        removeOptionalTags: false

I need quotes and a closing body tag for our infrastructure

or can I inherit it and overwrite it ?

**Comment by Conduitry** [comment] 2020-09-16 12:00
Not currently, there's an issue for it - #348.
