### ISSUE TITLE
(v3) `preload` in context="module" not registering until restart

### ISSUE THREAD

**Issue by arxpoetica** [sveltejs/sapper#611] opened 2019-03-16 19:13 UTC
This *might* be a Svelte issue, but filing it here.

There's a weird thing happens in v3 Sapper/Svelte where `preload` works in some components/pages and not others. Even identical code within `preload`.

Turns out it _does_ work the same in these components/pages. One just has to completely restart Sapper for the new `context="module"` script to register the preload.

Example without restart:

Given:

```
<script>export let user;</script>
```

One will see the following error:

> <Users> was created without expected prop 'user'

Restarting, the error goes away, and preload works.

**Comment by Conduitry** [comment] 2019-07-28 16:40
I'm hoping this was fixed in 0.27.5 by #713.

**Comment by tkroll** [comment] 2019-08-02 00:52
Still seeing this in v0.27.8.

**Comment by ematipico** [comment] 2019-08-02 09:23
I can confirm that I'm still seeing this issue

**Comment by sanderhahn** [comment] 2019-08-12 23:18
The `create_manifest_data` function has the logic `has_preload` (https://github.com/sveltejs/sapper/blob/master/src/core/create_manifest_data.ts#L16) which value is cached in the `data_manifest.components` structure. When files in the `src/routes` are updated the preloads are rechecked, however this doesn't happen when the content of an individual page is updated. So this problem seem to occur when an empty route/page is added and the `preload` function is added/removed at a later time. The preload is important because it affects the code generation in `create_app` (https://github.com/sveltejs/sapper/blob/22389eab992355b948ca6ce5a28e39ab1947ccac/src/core/create_app.ts#L169).

**Closed** 2019-09-24 00:38 UTC
Labels: bug
