### ISSUE TITLE
CSS selectors removed when actually still in use

### ISSUE THREAD

**Issue by happycollision** [sveltejs/sapper#842] opened 2019-08-11 05:50 UTC
**Describe the bug**
Sapper/Svelte's unused CSS selector feature is removing some styles which are still in use. The edge case in which this happens is probably rare, but is something to be aware of. I am new to Svelte and Sapper, so I may be wrong about "why", but you can reproduce the "what" via the steps below.

When two route components define the exact same styles, only one is loaded into the DOM. (This is expected.) However, if one of those route components happens to have declared an unused selector, it is stripped from the style definition. If you visit the missing style route first, then follow a link to the other route which has the same style definitions, the previously unused selector _remains stripped_ from the page. So even if the second route uses the style properly, it will be missing.

Admittedly, fixing the warning that the styles are unused will make the two definitions have a different hash, and therefore both will be loaded (and nothing will be stripped anyway). However, it is a _warning_ and not an _error_ that is thrown, so perhaps there is some concern there.

**Logs**
(Just some expected logs about unused css selectors)

**To Reproduce**
1. Follow directions to start your first Sapper app: `npx degit "sveltejs/sapper-template#webpack" my-app`
2. Copy `src/routes/index.svelte` to `src/routes/missing.svelte`
3. Remove the `<figure>` entirely from the `missing.svelte` file. Do not adjust the styles.
4. `npm run dev` (observe the "Unused CSS selector" warnings) and navigate to `localhost:3000/missing`.
5. Click the home link.

Expected: Borat whose width does not exceed 400px.
Observed: Huge Borat.

6. Reload the page, and: Borat whose width does not exceed 400px.

**Information about your Sapper Installation:**
- Your browser and the version: **Safari (doesn't matter)**
- Your operating system: **macOS Mojave latest (probably doesn't matter)**
- Your hosting environment: **(local dev)**
- Sapper version **0.27.8**
- Svelte version **3.7.1**
- If it is an exported (npm run export) or dynamic application: **exported**
- Whether your application uses Webpack or Rollup: **Webpack**

**Severity**
Trivial. It is very easy to fix if the developer who is running into it knows what is going on, but it is surprising.

**Comment by happycollision** [comment] 2019-08-11 05:54
(The repro is pretty funny, though.)
<img width="869" alt="Screen Shot 2019-08-11 at 12 53 54 AM" src="https://user-images.githubusercontent.com/3663628/62830315-95aa4100-bbd2-11e9-99f7-0c41afb86df0.png">

**Comment by mrbianchi** [comment] 2020-04-18 17:20
same

**Comment by Conduitry** [comment] 2020-04-19 13:41
Duplicate of https://github.com/sveltejs/svelte/issues/4313

**Closed by Conduitry** 2020-04-19 13:41 UTC
Labels: bug
